### This code is for extracting data from the [cais/mmlu](https://huggingface.co/datasets/cais/mmlu) dataset from HuggingFace.

In [47]:
import pandas as pd
import numpy as np

In [59]:
category = "professional_law"     # Replace this to other categories if necessary
split = f"{category}/test-00000-of-00001.parquet"
df = pd.read_parquet("hf://datasets/cais/mmlu/" + split)

df.head()

,question,subject,choices,answer
0,"One afternoon, a pilot was flying a small airp...",professional_law,"[admissible, because the attorney-client privi...",2
1,"A state statute provides: ""Whenever a person k...",professional_law,"[not guilty, if the arrest was unlawful withou...",1
2,A taxpayer was notified by the government that...,professional_law,"[inadmissible, because it would violate the at...",3
3,A resident announced his candidacy for state r...,professional_law,[The resident's petition contained a large num...,2
4,A defendant was angry at his friend for marryi...,professional_law,[He intended to kill the friend and not the da...,1

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1534 entries, 0 to 1533
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   question  1534 non-null   object
 1   subject   1534 non-null   object
 2   choices   1534 non-null   object
 3   answer    1534 non-null   int64
dtypes: int64(1), object(3)
memory usage: 48.1+ KB

In [61]:
df.drop(columns=['subject'], inplace=True)
df.head()

,question,choices,answer
0,"One afternoon, a pilot was flying a small airp...","[admissible, because the attorney-client privi...",2
1,"A state statute provides: ""Whenever a person k...","[not guilty, if the arrest was unlawful withou...",1
2,A taxpayer was notified by the government that...,"[inadmissible, because it would violate the at...",3
3,A resident announced his candidacy for state r...,[The resident's petition contained a large num...,2
4,A defendant was angry at his friend for marryi...,[He intended to kill the friend and not the da...,1

In [62]:
option_a = []
option_b = []
option_c = []
option_d = []

for choices in df['choices']:
  option_a.append(choices[0])
  option_b.append(choices[1])
  option_c.append(choices[2])
  option_d.append(choices[3])

# print(df['choices'][1])

# print(option_a[1])
# print(option_b[1])
# print(option_c[1])
# print(option_d[1])

In [63]:
id_column = ['q' + str((index+1)) for index in df.index]

In [64]:
df['answer'].head()

0    2
1    1
2    3
3    2
4    1
Name: answer, dtype: int64

In [68]:
answer = []

for i in range(len(df)):
  if df['answer'][i] == 0:
    answer.append('A')
  elif df['answer'][i] == 1:
    answer.append('B')
  elif df['answer'][i] == 2:
    answer.append('C')
  else:
    answer.append('D')

answer[:5]

['C', 'B', 'D', 'C', 'B']

In [69]:
formatted_df = {'id' : id_column,
                'question' : df['question'],
                'option_a' : option_a,
                'option_b' : option_b,
                'option_c' : option_c,
                'option_d' : option_d,
                'answer' : answer}
formatted_df = pd.DataFrame(formatted_df)
formatted_df.head()

,id,question,option_a,option_b,option_c,option_d,answer
0,q1,"One afternoon, a pilot was flying a small airp...","admissible, because the attorney-client privil...","admissible, because there is no privilege of c...","inadmissible, because the attorney-client priv...","inadmissible, because it was a statement of ph...",C
1,q2,"A state statute provides: ""Whenever a person k...","not guilty, if the arrest was unlawful without...","not guilty, if the arrest was lawful, provided...","guilty, if the arrest was lawful, regardless w...","guilty, if the arrest was unlawful, regardless...",B
2,q3,A taxpayer was notified by the government that...,"inadmissible, because it would violate the att...","inadmissible, because it would violate the tax...",inadmissible as violative of the work-product ...,admissible as an admission.,D
3,q4,A resident announced his candidacy for state r...,The resident's petition contained a large numb...,A similar authenticating statute was held to b...,The authenticating requirement was necessary t...,Two other candidates had successfully petition...,C
4,q5,A defendant was angry at his friend for marryi...,He intended to kill the friend and not the dau...,He intended only to wound the friend.,He was unaware of the elements of malice.,The killing was the result of negligence in mi...,B

In [ ]:
formatted_df.to_csv(f'./data/{category}_dataset.csv', index=False)